"""empty message

Revision ID: 1f51db120b38
Revises: 83224b571155
Create Date: 2026-05-26 06:23:14.118609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f51db120b38'
down_revision = '83224b571155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('responsibilites', sa.String(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('type_of_contract', sa.Enum('B2B', 'DZIEŁO', 'UOP', 'ZLECENIE', 'ZASTEPSTWO', 'PRAKTYKI', name='joboffertype'), nullable=False),
    sa.Column('level', sa.Enum('PRAKTYKANT', 'JUNIOR', 'MID', 'SENIOR', 'EKSPERT', 'KIEROWNIK', 'MANAGER', 'DYREKTOR', 'PREZES', name='level'), nullable=False),
    sa.Column('job_type', sa.Enum('ZDALNA', 'HYBRYDOWA', 'STACJONARNA', name='jobtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expired', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_offer')
    # ### end Alembic commands ###
