"""empty message

Revision ID: 3f80e62d22bd
Revises: aa01338c2d26
Create Date: 2026-05-27 18:55:50.529565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f80e62d22bd'
down_revision = 'aa01338c2d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.alter_column('recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
