"""empty message

Revision ID: 45515bddefbb
Revises: acaeeab6dda7
Create Date: 2026-06-06 06:51:33.017813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45515bddefbb'
down_revision = 'acaeeab6dda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_application', ['user_id', 'job_offer_id'])

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recruiter_id')

    with op.batch_alter_table('saved_job_offer', schema=None) as batch_op:
        batch_op.alter_column('job_offer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('uq_saved_job', ['user_id', 'job_offer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_job_offer', schema=None) as batch_op:
        batch_op.drop_constraint('uq_saved_job', type_='unique')
        batch_op.alter_column('job_offer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('job_offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruiter_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['recruiter_id'], ['id'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint('uq_application', type_='unique')

    # ### end Alembic commands ###
