"""Change status of application to polish version

Revision ID: 5305707a4e7b
Revises: a3ac4dde080f
Create Date: 2026-06-09 06:33:42.705832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5305707a4e7b'
down_revision = 'a3ac4dde080f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ZAAPLIKOWANO', 'SELEKCJA', 'ROZMOWA', 'OFERTA', 'ZATRUDNIONY', 'ODRZUCONY', name='applicationstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ZAAPLIKOWANO', 'SELEKCJA', 'ROZMOWA', 'OFERTA', 'ZATRUDNIONY', 'ODRZUCONY', name='applicationstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
