"""Add email column to user table

Revision ID: 83224b571155
Revises: f8397d61fa3c
Create Date: 2026-05-22 11:01:22.261771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83224b571155'
down_revision = 'f8397d61fa3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(
    'uq_user_email',
    ['email']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
