"""initial

Revision ID: aa01338c2d26
Revises: 
Create Date: 2026-05-27 18:48:54.957046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa01338c2d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('JOB_SEEKER', 'RECRUITER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('job_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsibilities', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('type_of_contract', sa.Enum('B2B', 'DZIEŁO', 'UOP', 'ZLECENIE', 'ZASTEPSTWO', 'PRAKTYKI', name='joboffertype'), nullable=False),
    sa.Column('level', sa.Enum('PRAKTYKANT', 'JUNIOR', 'MID', 'SENIOR', 'EKSPERT', 'KIEROWNIK', 'MANAGER', 'DYREKTOR', 'PREZES', name='level'), nullable=False),
    sa.Column('job_type', sa.Enum('ZDALNA', 'HYBRYDOWA', 'STACJONARNA', name='jobtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_offer_id'], ['job_offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('job_offer')
    op.drop_table('user')
    # ### end Alembic commands ###
